- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address

